# Generated by Django 5.2.7 on 2025-10-28 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grup_adi', models.CharField(max_length=100)),
                ('grup_resmi', models.ImageField(blank=True, null=True, upload_to='grup_resimleri/')),
                ('yonetici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yönettigi_gruplar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OyuncuProfili',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mevkii', models.CharField(choices=[('KL', 'Kaleci'), ('DF', 'Defans'), ('OS', 'Orta Saha'), ('FR', 'Forvet'), ('CY', 'Çok Yönlü')], default='CY', max_length=2)),
                ('profil_resmi', models.ImageField(blank=True, null=True, upload_to='profil_resimleri/')),
                ('yetkili_puan', models.IntegerField(default=5, help_text='Yönetici tarafından verilen yetenek puanı (1-10)')),
                ('kisilik_puani', models.IntegerField(default=5, help_text='Yönetici tarafından verilen kişilik puanı (1-10)')),
                ('kullanici', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrupOyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onay_durumu', models.CharField(choices=[('B', 'Beklemede'), ('O', 'Onaylandı'), ('R', 'Reddedildi')], default='B', max_length=1)),
                ('oynadigi_mac', models.IntegerField(default=0)),
                ('kazandigi_mac', models.IntegerField(default=0)),
                ('kaybettigi_mac', models.IntegerField(default=0)),
                ('berabere_mac', models.IntegerField(default=0)),
                ('gol', models.IntegerField(default=0)),
                ('asist', models.IntegerField(default=0)),
                ('sari_kart', models.IntegerField(default=0)),
                ('kirmizi_kart', models.IntegerField(default=0)),
                ('toplam_seviye_puani', models.IntegerField(default=0)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grup_yonetimi.grup')),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('grup', 'oyuncu')},
            },
        ),
    ]
