# Generated by Django 5.2.7 on 2025-10-28 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup_yonetimi', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateTimeField()),
                ('yer', models.CharField(blank=True, max_length=200, null=True)),
                ('takim_a_skor', models.IntegerField(default=0)),
                ('takim_b_skor', models.IntegerField(default=0)),
                ('oynandi_mi', models.BooleanField(default=False)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grup_yonetimi.grup')),
            ],
        ),
        migrations.CreateModel(
            name='MacOyuncu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('takim', models.CharField(blank=True, choices=[('A', 'Takım A'), ('B', 'Takım B')], max_length=1, null=True)),
                ('gol', models.IntegerField(default=0)),
                ('asist', models.IntegerField(default=0)),
                ('sari_kart', models.IntegerField(default=0)),
                ('kirmizi_kart', models.IntegerField(default=0)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grup_yonetimi.mac')),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mac', 'oyuncu')},
            },
        ),
    ]
