# Generated by Django 5.2.7 on 2025-10-28 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup_yonetimi', '0002_mac_macoyuncu'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupAyarlari',
            fields=[
                ('grup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='grup_yonetimi.grup')),
                ('min_mac_grup_puani', models.IntegerField(default=5, help_text='Grupta bu kadar maç oynayan oyuncu, sadece grup içi puan ortalaması ile değerlendirilir.')),
                ('min_mac_genel_puani', models.IntegerField(default=10, help_text='Toplamda bu kadar maç oynayan oyuncu, genel puan ortalaması ile değerlendirilir.')),
            ],
        ),
    ]
