# Generated by Django 5.2.7 on 2025-10-28 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup_yonetimi', '0003_grupayarlari'),
    ]

    operations = [
        migrations.AddField(
            model_name='mac',
            name='denge_farki',
            field=models.IntegerField(default=0, help_text='İki takım arasındaki puan farkı.'),
        ),
        migrations.AddField(
            model_name='mac',
            name='takim_a_denge_puani',
            field=models.IntegerField(default=0, help_text="Takım A'nın dengeleme için kullanılan toplam puanı."),
        ),
        migrations.AddField(
            model_name='mac',
            name='takim_b_denge_puani',
            field=models.IntegerField(default=0, help_text="Takım B'nin dengeleme için kullanılan toplam puanı."),
        ),
    ]
