# Generated by Django 5.2.7 on 2025-10-29 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup_yonetimi', '0004_mac_denge_farki_mac_takim_a_denge_puani_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mac',
            name='saat',
            field=models.TimeField(default='19:00:00', verbose_name='Maç Saati'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mac',
            name='oynandi_mi',
            field=models.BooleanField(default=False, verbose_name='Oynandı mı?'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='tarih',
            field=models.DateField(verbose_name='Maç Tarihi'),
        ),
        migrations.AlterField(
            model_name='mac',
            name='yer',
            field=models.CharField(default='-', max_length=255, verbose_name='Maç Yeri'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MacKatilim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katilim_zamani', models.DateTimeField(auto_now_add=True)),
                ('mac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='katilimlar', to='grup_yonetimi.mac')),
                ('oyuncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maç Katılımı',
                'verbose_name_plural': 'Maç Katılımları',
                'unique_together': {('mac', 'oyuncu')},
            },
        ),
    ]
