# Generated by Django 5.2.7 on 2025-11-05 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grup_yonetimi', '0005_mac_saat_alter_mac_oynandi_mi_alter_mac_tarih_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grup',
            name='herkese_gorunur',
            field=models.BooleanField(default=True, verbose_name='Herkese Açık (Listelensin mi?)'),
        ),
        migrations.CreateModel(
            name='GrupDavet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durum', models.CharField(choices=[('B', 'Beklemede'), ('K', 'Kabul Edildi'), ('R', 'Reddedildi')], default='B', max_length=1)),
                ('davet_zamani', models.DateTimeField(auto_now_add=True)),
                ('davet_edilen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alınan_davetler', to=settings.AUTH_USER_MODEL)),
                ('gonderen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gonderilen_davetler', to=settings.AUTH_USER_MODEL)),
                ('grup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='davetler', to='grup_yonetimi.grup')),
            ],
            options={
                'verbose_name': 'Grup Daveti',
                'verbose_name_plural': 'Grup Davetleri',
                'unique_together': {('grup', 'davet_edilen')},
            },
        ),
    ]
